openapi: 3.1.0
info:
  title: Automata API
  description: API for web operating
  version: 1.0.0

paths:
  /api/v1/run-task:
    post:
      summary: Run a new automation task
      description: Creates and executes a new web automation task
      operationId: runTask
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - task
              properties:
                task:
                  type: string
                  description: Description of the task to be performed
                  example: "Click on the login button and fill in credentials"
                url:
                  type: string
                  format: uri
                  description: Target URL for the automation task
                  example: "https://example.com/login"
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Unique task identifier
                    example: "123e4567-e89b-12d3-a456-426614174000"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/task/{id}:
    get:
      summary: Get task details
      description: Retrieves detailed information about a specific task (excluding screenshots)
      operationId: getTask
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: Task details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/task/{id}/status:
    get:
      summary: Get task status
      description: Retrieves the current status of a specific task
      operationId: getTaskStatus
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: Task status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    type: string
                    enum: [pending, running, completed, failed]
                    example: "completed"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/task/{id}/screenshots:
    get:
      summary: Get task screenshots
      description: Retrieves all screenshots captured during task execution
      operationId: getTaskScreenshots
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: Screenshots retrieved successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - screenshots
                properties:
                  screenshots:
                    type: array
                    items:
                      type: string
                      description: Base64 encoded screenshot or screenshot URL
                    example: ["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."]
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/task/{id}/gif:
    get:
      summary: Get task gif
      description: Retrieves the gif generated from task screenshots
      operationId: getTaskGif
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: Gif retrieved successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - gif
                properties:
                  gif:
                    type: string
                    description: Base64 encoded gif
                    example: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP..."
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    Step:
      type: object
      required:
        - next_goal
        - evaluation_previous_goal
        - previous_success
      properties:
        next_goal:
          type: string
          description: The next goal or action to be performed
          example: "Click on the submit button"
        evaluation_previous_goal:
          type: string
          description: Evaluation of the previous goal execution
          example: "Successfully filled in the username field"
        previous_success:
          type: boolean
          description: Whether the previous step was successful
          example: true

    Task:
      type: object
      required:
        - id
        - task
        - url
        - status
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
          example: "123e4567-e89b-12d3-a456-426614174000"
        task:
          type: string
          description: Description of the task
          example: "Click on the login button and fill in credentials"
        url:
          type: string
          format: uri
          description: Target URL for the automation task
          example: "https://example.com/login"
        status:
          type: string
          enum: [pending, running, completed, failed]
          description: Current task status
          example: "completed"
        steps:
          type: array
          items:
            $ref: '#/components/schemas/Step'
          description: List of step objects executed during the task
          example:
            - next_goal: "Navigate to login page"
              evaluation_previous_goal: "Page loaded successfully"
              previous_success: true
            - next_goal: "Fill username field"
              evaluation_previous_goal: "Login page elements found"
              previous_success: true
        output:
          type: string
          description: Task execution output or result
          example: "Login successful"

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message or error object
          example: "Error Message"
